dubbo:
  application:
    name: dubbo-springboot-demo-provider
    qos-port: 33332
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: nacos://${nacos.address:localhost}:8848?username=nacos&password=nacos